[project]
name = "fundamentals-ds"
version = "0.1.0"
description = "Apuntes en notebooks sobre los fundamentos de la ciencia de datos"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "gensim>=4.4.0",
    "imbalanced-learn>=0.14.2",
    "jupyterlab>=4.6.4",
    "matplotlib>=3.11.2",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "spacy>=3.8.16",
    "statsmodels>=0.15.0",
    "torch>=2.14.1",
    "torchvision>=0.29.1",
    "transformers>=5.18.0",
    "umap-learn>=0.5.12",
]
